export const disableNavWithFooter = [
  '/not-found',
  '/dashboard',
  '/dashboard/settings',
  '/dashboard/profile',
  '/dashboard/students',
  '/dashboard/programs',
  '/dashboard/payments',
  '/dashboard/users',
  '/dashboard/bookmarks',
  '/dashboard/comments',
  '/dashboard/newsletters',
  '/dashboard/posts',
  '/login',
  '/register',
  '/forgot-password',
  '/dashboard/coast-craft/posts',
];
